"""tar.gz packing logic."""

from __future__ import annotations

import logging
import tarfile
import tempfile
from pathlib import Path

from pydepot.detector import detect_project
from pydepot.manifest import write_manifest
from pydepot.models import Manifest, PackageFile, PackOptions, ProjectInfo
from pydepot.platforms import PlatformTag, get_python_version, resolve_platforms
from pydepot.resolver import download_packages

logger = logging.getLogger(__name__)


def _generate_readme(manifest: Manifest) -> str:
    """Generate README.md content for the offline bundle."""
    package_names = sorted({p.name for p in manifest.packages})
    packages_list = "\n".join(f"  - {name}" for name in package_names)

    return f"""# {manifest.project_name} {manifest.project_version} - Offline Installation Package

## Installation

To install all packages from this offline bundle, run:

```bash
pip install --no-index --find-links ./packages {" ".join(package_names)}
```

## Contents

- **Project**: {manifest.project_name} {manifest.project_version}
- **Python version**: {manifest.python_version}
- **Platforms**: {", ".join(manifest.platforms)}
- **Total packages**: {manifest.package_count}
- **Total size**: {manifest.total_size / 1024 / 1024:.1f} MB

### Packages

{packages_list}

## Generated by

PyDepot ({manifest.created_by})
"""


def _create_bundle_tarball(
    output_path: Path,
    bundle_name: str,
    manifest: Manifest,
    packages_dir: Path,
) -> Path:
    """Create the final .tar.gz bundle.

    Args:
        output_path: Directory to write the tarball to.
        bundle_name: Name for the bundle (used as top-level directory in tar).
        manifest: The manifest object.
        packages_dir: Directory containing downloaded packages.

    Returns:
        Path to the created .tar.gz file.
    """
    tarball_path = output_path / f"{bundle_name}.tar.gz"
    output_path.mkdir(parents=True, exist_ok=True)

    with tarfile.open(tarball_path, "w:gz") as tar:
        # Add README.md
        readme_content = _generate_readme(manifest).encode("utf-8")
        readme_info = tarfile.TarInfo(name=f"{bundle_name}/README.md")
        readme_info.size = len(readme_content)
        tar.addfile(readme_info, fileobj=__import__("io").BytesIO(readme_content))

        # Add manifest.json
        with tempfile.NamedTemporaryFile(suffix=".json", delete=False) as tmp:
            tmp_path = Path(tmp.name)
        try:
            write_manifest(manifest, tmp_path)
            tar.add(tmp_path, arcname=f"{bundle_name}/manifest.json")
        finally:
            tmp_path.unlink(missing_ok=True)

        # Add package files
        for pkg in manifest.packages:
            pkg_file = packages_dir / pkg.filename
            if pkg_file.exists():
                tar.add(pkg_file, arcname=f"{bundle_name}/packages/{pkg.filename}")

    return tarball_path


class PackBuilder:
    """High-level API for building offline installation bundles."""

    def __init__(self, options: PackOptions) -> None:
        self.options = options

    def build(self) -> Path:
        """Build the offline bundle.

        Returns:
            Path to the created .tar.gz file.

        Raises:
            FileNotFoundError: If project path doesn't exist.
            ValueError: If project can't be detected.
            RuntimeError: If download fails.
        """
        # Detect project
        project_info = detect_project(self.options.project_path)
        logger.info(
            "Detected project: %s %s (manager: %s)",
            project_info.name,
            project_info.version,
            project_info.manager.value if project_info.manager else "unknown",
        )

        # Resolve platforms
        platforms = resolve_platforms(self.options.platforms or None)
        logger.info("Target platforms: %s", [str(p) for p in platforms])

        # Determine Python version
        python_version = self.options.python_version or get_python_version()

        # Download packages to temp dir
        with tempfile.TemporaryDirectory() as tmp_dir:
            packages_dir = Path(tmp_dir) / "packages"
            packages_dir.mkdir()

            packages = download_packages(
                project_info=project_info,
                download_dir=packages_dir,
                platforms=platforms,
                python_version=python_version,
                exclude=self.options.exclude or None,
                include_extras=self.options.include_extras or None,
            )

            logger.info("Downloaded %d package files", len(packages))

            # Build manifest
            manifest = Manifest(
                project_name=project_info.name,
                project_version=project_info.version,
                python_version=python_version,
                platforms=[str(p) for p in platforms],
                packages=packages,
            )

            # Create bundle
            bundle_name = f"{project_info.name}-{project_info.version}-offline"
            output_dir = self.options.output_dir.resolve()

            tarball_path = _create_bundle_tarball(
                output_path=output_dir,
                bundle_name=bundle_name,
                manifest=manifest,
                packages_dir=packages_dir,
            )

            logger.info("Created bundle: %s", tarball_path)
            return tarball_path
